// Code generated by ent, DO NOT EDIT.

package tag

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tag type in the database.
	Label = "tag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeCps holds the string denoting the cps edge name in mutations.
	EdgeCps = "cps"
	// Table holds the table name of the tag in the database.
	Table = "tags"
	// CpsTable is the table that holds the cps relation/edge. The primary key declared below.
	CpsTable = "cp_tags"
	// CpsInverseTable is the table name for the CP entity.
	// It exists in this package in order to avoid circular dependency with the "cp" package.
	CpsInverseTable = "cps"
)

// Columns holds all SQL columns for tag fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// CpsPrimaryKey and CpsColumn2 are the table columns denoting the
	// primary key for the cps relation (M2M).
	CpsPrimaryKey = []string{"cp_id", "tag_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() int64
)

// OrderOption defines the ordering options for the Tag queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCpsCount orders the results by cps count.
func ByCpsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCpsStep(), opts...)
	}
}

// ByCps orders the results by cps terms.
func ByCps(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCpsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCpsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CpsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, CpsTable, CpsPrimaryKey...),
	)
}
