// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CpsColumns holds the columns for the "cps" table.
	CpsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "category", Type: field.TypeString, Size: 20},
		{Name: "link", Type: field.TypeString, Nullable: true},
	}
	// CpsTable holds the schema information for the "cps" table.
	CpsTable = &schema.Table{
		Name:       "cps",
		Columns:    CpsColumns,
		PrimaryKey: []*schema.Column{CpsColumns[0]},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// CpTagsColumns holds the columns for the "cp_tags" table.
	CpTagsColumns = []*schema.Column{
		{Name: "cp_id", Type: field.TypeInt64},
		{Name: "tag_id", Type: field.TypeInt64},
	}
	// CpTagsTable holds the schema information for the "cp_tags" table.
	CpTagsTable = &schema.Table{
		Name:       "cp_tags",
		Columns:    CpTagsColumns,
		PrimaryKey: []*schema.Column{CpTagsColumns[0], CpTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cp_tags_cp_id",
				Columns:    []*schema.Column{CpTagsColumns[0]},
				RefColumns: []*schema.Column{CpsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "cp_tags_tag_id",
				Columns:    []*schema.Column{CpTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CpsTable,
		TagsTable,
		CpTagsTable,
	}
)

func init() {
	CpTagsTable.ForeignKeys[0].RefTable = CpsTable
	CpTagsTable.ForeignKeys[1].RefTable = TagsTable
}
