// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CpsColumns holds the columns for the "cps" table.
	CpsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "category", Type: field.TypeString, Size: 20},
		{Name: "link", Type: field.TypeString, Nullable: true},
		{Name: "user_cps", Type: field.TypeInt64},
	}
	// CpsTable holds the schema information for the "cps" table.
	CpsTable = &schema.Table{
		Name:       "cps",
		Columns:    CpsColumns,
		PrimaryKey: []*schema.Column{CpsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cps_users_cps",
				Columns:    []*schema.Column{CpsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "content", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "cp_comments", Type: field.TypeInt64},
		{Name: "comment_children", Type: field.TypeInt64, Nullable: true},
		{Name: "user_comments", Type: field.TypeInt64},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_cps_comments",
				Columns:    []*schema.Column{CommentsColumns[3]},
				RefColumns: []*schema.Column{CpsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "comments_comments_children",
				Columns:    []*schema.Column{CommentsColumns[4]},
				RefColumns: []*schema.Column{CommentsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "comments_users_comments",
				Columns:    []*schema.Column{CommentsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "user_tags", Type: field.TypeInt64},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tags_users_tags",
				Columns:    []*schema.Column{TagsColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "sub", Type: field.TypeString, Unique: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// CpTagsColumns holds the columns for the "cp_tags" table.
	CpTagsColumns = []*schema.Column{
		{Name: "cp_id", Type: field.TypeInt64},
		{Name: "tag_id", Type: field.TypeInt64},
	}
	// CpTagsTable holds the schema information for the "cp_tags" table.
	CpTagsTable = &schema.Table{
		Name:       "cp_tags",
		Columns:    CpTagsColumns,
		PrimaryKey: []*schema.Column{CpTagsColumns[0], CpTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "cp_tags_cp_id",
				Columns:    []*schema.Column{CpTagsColumns[0]},
				RefColumns: []*schema.Column{CpsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "cp_tags_tag_id",
				Columns:    []*schema.Column{CpTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserLikedCpsColumns holds the columns for the "user_liked_cps" table.
	UserLikedCpsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "cp_id", Type: field.TypeInt64},
	}
	// UserLikedCpsTable holds the schema information for the "user_liked_cps" table.
	UserLikedCpsTable = &schema.Table{
		Name:       "user_liked_cps",
		Columns:    UserLikedCpsColumns,
		PrimaryKey: []*schema.Column{UserLikedCpsColumns[0], UserLikedCpsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_liked_cps_user_id",
				Columns:    []*schema.Column{UserLikedCpsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_liked_cps_cp_id",
				Columns:    []*schema.Column{UserLikedCpsColumns[1]},
				RefColumns: []*schema.Column{CpsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CpsTable,
		CommentsTable,
		TagsTable,
		UsersTable,
		CpTagsTable,
		UserLikedCpsTable,
	}
)

func init() {
	CpsTable.ForeignKeys[0].RefTable = UsersTable
	CommentsTable.ForeignKeys[0].RefTable = CpsTable
	CommentsTable.ForeignKeys[1].RefTable = CommentsTable
	CommentsTable.ForeignKeys[2].RefTable = UsersTable
	TagsTable.ForeignKeys[0].RefTable = UsersTable
	CpTagsTable.ForeignKeys[0].RefTable = CpsTable
	CpTagsTable.ForeignKeys[1].RefTable = TagsTable
	UserLikedCpsTable.ForeignKeys[0].RefTable = UsersTable
	UserLikedCpsTable.ForeignKeys[1].RefTable = CpsTable
}
