// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cp-website/ent/cp"
	"cp-website/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CP is the model entity for the CP schema.
type CP struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Link holds the value of the "link" field.
	Link string `json:"link,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CPQuery when eager-loading is set.
	Edges        CPEdges `json:"edges"`
	user_cps     *int64
	selectValues sql.SelectValues
}

// CPEdges holds the relations/edges for other nodes in the graph.
type CPEdges struct {
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// LikedByUsers holds the value of the liked_by_users edge.
	LikedByUsers []*User `json:"liked_by_users,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e CPEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[0] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CPEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// LikedByUsersOrErr returns the LikedByUsers value or an error if the edge
// was not loaded in eager-loading.
func (e CPEdges) LikedByUsersOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.LikedByUsers, nil
	}
	return nil, &NotLoadedError{edge: "liked_by_users"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e CPEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[3] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CP) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cp.FieldID:
			values[i] = new(sql.NullInt64)
		case cp.FieldName, cp.FieldCategory, cp.FieldLink:
			values[i] = new(sql.NullString)
		case cp.ForeignKeys[0]: // user_cps
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CP fields.
func (_m *CP) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cp.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case cp.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case cp.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case cp.FieldLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link", values[i])
			} else if value.Valid {
				_m.Link = value.String
			}
		case cp.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_cps", value)
			} else if value.Valid {
				_m.user_cps = new(int64)
				*_m.user_cps = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CP.
// This includes values selected through modifiers, order, etc.
func (_m *CP) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTags queries the "tags" edge of the CP entity.
func (_m *CP) QueryTags() *TagQuery {
	return NewCPClient(_m.config).QueryTags(_m)
}

// QueryOwner queries the "owner" edge of the CP entity.
func (_m *CP) QueryOwner() *UserQuery {
	return NewCPClient(_m.config).QueryOwner(_m)
}

// QueryLikedByUsers queries the "liked_by_users" edge of the CP entity.
func (_m *CP) QueryLikedByUsers() *UserQuery {
	return NewCPClient(_m.config).QueryLikedByUsers(_m)
}

// QueryComments queries the "comments" edge of the CP entity.
func (_m *CP) QueryComments() *CommentQuery {
	return NewCPClient(_m.config).QueryComments(_m)
}

// Update returns a builder for updating this CP.
// Note that you need to call CP.Unwrap() before calling this method if this CP
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CP) Update() *CPUpdateOne {
	return NewCPClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CP entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CP) Unwrap() *CP {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CP is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CP) String() string {
	var builder strings.Builder
	builder.WriteString("CP(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("link=")
	builder.WriteString(_m.Link)
	builder.WriteByte(')')
	return builder.String()
}

// CPs is a parsable slice of CP.
type CPs []*CP
