// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cp-website/ent/cp"
	"cp-website/ent/schema"
	"cp-website/ent/tag"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cpFields := schema.CP{}.Fields()
	_ = cpFields
	// cpDescName is the schema descriptor for name field.
	cpDescName := cpFields[1].Descriptor()
	// cp.NameValidator is a validator for the "name" field. It is called by the builders before save.
	cp.NameValidator = cpDescName.Validators[0].(func(string) error)
	// cpDescCategory is the schema descriptor for category field.
	cpDescCategory := cpFields[2].Descriptor()
	// cp.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	cp.CategoryValidator = func() func(string) error {
		validators := cpDescCategory.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(category string) error {
			for _, fn := range fns {
				if err := fn(category); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// cpDescID is the schema descriptor for id field.
	cpDescID := cpFields[0].Descriptor()
	// cp.DefaultID holds the default value on creation for the id field.
	cp.DefaultID = cpDescID.Default.(func() int64)
	tagFields := schema.Tag{}.Fields()
	_ = tagFields
	// tagDescName is the schema descriptor for name field.
	tagDescName := tagFields[1].Descriptor()
	// tag.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tag.NameValidator = tagDescName.Validators[0].(func(string) error)
	// tagDescID is the schema descriptor for id field.
	tagDescID := tagFields[0].Descriptor()
	// tag.DefaultID holds the default value on creation for the id field.
	tag.DefaultID = tagDescID.Default.(func() int64)
}
