name: Build Action  # 工作流的名称

on:
  push:
    tags:
      - 'v*'

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
          cache: true
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm' # 自动缓存 pnpm 依赖
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Verify versions
        run: |
          go version
          node -v
          pnpm -v
      
      - name: Install dependencies
        continue-on-error: true
        run: |
          cd website
          pnpm install --frozen-lockfile
          pnpm approve-builds --all

      - name: Build Frontend
        run: |
          pnpm build
          # 假设你的 SvelteKit 导出目录是 website/build
          # 确保 pb_public 文件夹存在
          mkdir -p ../pb_public
          cp -r build/* ../pb_public/
      
      - name: Build Go Binary
        run: |
          # 禁用 CGO 以实现静态链接，确保二进制文件在不同 Linux 发行版都能跑
          export CGO_ENABLED=0
          
          # 编译 Linux 版本
          GOOS=linux GOARCH=amd64 go build -o myapp-linux main.go
          
          # 编译 Windows 版本
          GOOS=windows GOARCH=amd64 go build -o myapp-windows.exe main.go

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            pdnode-cp-linux
            pdnode-cp-windows.exe
          # 这里的 token 是 GitHub 自动提供的，不需要你手动设置
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true # 自动根据 commit 生成更新日志