// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CP is the predicate function for cp builders.
type CP func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
